services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
  
  game:
    build:
      context: ./game/Export
    ports:
      - "8082:8082"
    depends_on:
      - backend

  student:
    build:
      context: ./frontend/student_portal
    ports:
      - "8080:8080"
    depends_on:
      - backend
  
  teacher:
    build:
      context: ./frontend/teacher_portal_tara
    ports:
      - "8081:8081"
    depends_on:
      - backend
  
  
